-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 18:08:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rh` DEFAULT CHARACTER SET utf8 ;
USE `rh` ;

-- -----------------------------------------------------
-- Table `rh`.`Funcionaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`Funcionaries` ;

CREATE TABLE IF NOT EXISTS `rh`.`Funcionaries` (
  `id_Funcionaries` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `responsabilidade` FLOAT NOT NULL,
  `trabalho em equipe` FLOAT NOT NULL,
  `inovador` FLOAT NOT NULL,
  `gerenciamento de risco` FLOAT NOT NULL,
  `salario` FLOAT NOT NULL,
  PRIMARY KEY (`id_Funcionaries`),
  UNIQUE INDEX `idFuncionaries_UNIQUE` (`id_Funcionaries` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rh`.`Funcionaries`
-- -----------------------------------------------------
START TRANSACTION;
USE `rh`;
INSERT INTO `rh`.`Funcionaries` (`id_Funcionaries`, `nome`, `responsabilidade`, `trabalho em equipe`, `inovador`, `gerenciamento de risco`, `salario`) VALUES (DEFAULT, 'FLAVIA', 4, 5, 3, 2, 1000);
INSERT INTO `rh`.`Funcionaries` (`id_Funcionaries`, `nome`, `responsabilidade`, `trabalho em equipe`, `inovador`, `gerenciamento de risco`, `salario`) VALUES (DEFAULT, 'OTAVIO', 4, 5, 3, 2, 2000);
INSERT INTO `rh`.`Funcionaries` (`id_Funcionaries`, `nome`, `responsabilidade`, `trabalho em equipe`, `inovador`, `gerenciamento de risco`, `salario`) VALUES (DEFAULT, 'LEO', 4, 5, 3, 2, 3000);
INSERT INTO `rh`.`Funcionaries` (`id_Funcionaries`, `nome`, `responsabilidade`, `trabalho em equipe`, `inovador`, `gerenciamento de risco`, `salario`) VALUES (DEFAULT, 'MARIA', 4, 5, 3, 2, 4000);
INSERT INTO `rh`.`Funcionaries` (`id_Funcionaries`, `nome`, `responsabilidade`, `trabalho em equipe`, `inovador`, `gerenciamento de risco`, `salario`) VALUES (DEFAULT, 'JOSE', 4, 5, 3, 2, 5000);

COMMIT;

