-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 19:20:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `grande` VARCHAR(45) CHARACTER SET 'armscii8' NOT NULL,
  `pequena` VARCHAR(45) NOT NULL,
  `media` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `idtb_pizza_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `preço` FLOAT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sem_borda` VARCHAR(45) NOT NULL,
  `com_borda` VARCHAR(45) NOT NULL,
  `sabor` VARCHAR(45) NOT NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`id_pizza`, `fk_categoria`),
  UNIQUE INDEX `idtb_pizza_UNIQUE` (`id_pizza` ASC) VISIBLE,
  INDEX `fk_tb_pizza_tb_categorias_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_tb_categorias`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
