-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 22:13:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cursoDaMinhaVida` DEFAULT CHARACTER SET utf8 ;
USE `db_cursoDaMinhaVida` ;

-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_categoria` (
  `idtb_categora` INT NOT NULL AUTO_INCREMENT,
  `curso_online` VARCHAR(45) NOT NULL,
  `curso_presencial` VARCHAR(45) NOT NULL,
  `curso_particular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_categora`),
  UNIQUE INDEX `idtb_categora_UNIQUE` (`idtb_categora` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_curso` (
  `idtb_curso` INT NOT NULL AUTO_INCREMENT,
  `ingles` VARCHAR(45) NOT NULL,
  `espanhol` VARCHAR(45) NOT NULL,
  `frances` VARCHAR(45) NOT NULL,
  `portugues` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `fk_tb_categoria` INT NOT NULL,
  PRIMARY KEY (`idtb_curso`, `fk_tb_categoria`),
  UNIQUE INDEX `idtb_curso_UNIQUE` (`idtb_curso` ASC) VISIBLE,
  INDEX `fk_tb_curso_tb_categora_idx` (`fk_tb_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_curso_tb_categora`
    FOREIGN KEY (`fk_tb_categoria`)
    REFERENCES `db_cursoDaMinhaVida`.`tb_categoria` (`idtb_categora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
